#!/bin/bash
if [[ -z "$(grep bq2562x_charger /etc/modules)"  ]];
then 
    echo "Adding bq2562x_charger to /etc/modules ..."
    echo 'bq2562x_charger' >> /etc/modules
    depmod || true
fi

echo "Please add 'dtoverlay=mrhat-bq25622' if needed, then reboot ..."
